### ISSUE TITLE
Errors related plugin being in CRLF

### ISSUE THREAD

**Issue by ghost** [summivox/vim-nfo#1]
When using this plugin on Linux I noticed these errors

```
Error detected while processing ~/.local/share/nvim/plugged/vim-nfo/ftdetect/nfo.vim:
line    1:
E488: Trailing characters
Press ENTER or type command to continue
Error detected while processing ~/.local/share/nvim/plugged/vim-nfo/ftdetect/nfo.vim:
line    2:
E15: Invalid expression: &enc != 'cp437' || ft != 'nfo'^M
Press ENTER or type command to continue
Error detected while processing ~/.local/share/nvim/plugged/vim-nfo/ftdetect/nfo.vim:
line    8:
E171: Missing :endif
```

It seems these are related to the plugin files being in CRLF. I fixed it by converting them to LF only.

```
sed -i 's/.$//' ./ftdetect/nfo.vim
sed -i 's/.$//' ./ftplugin/nfo.vim
```

**Comment by summivox** [comment]
Oh wow didn't know this... Never tried opening an NFO on Linux!
Thanks for fixing it! Could you please file a pull request?

**Comment by ghost** [comment]
Okay, this is really weird. I only seem to get the CR+LF terminators when checking out with `:PlugInstall` ie when using [VimPlug](https://github.com/junegunn/vim-plug). It's the only Plugin I have that does this.

```
$ file ~/.local/share/nvim/plugged/vim-nfo/ftdetect/nfo.vim 
~/.local/share/nvim/plugged/vim-nfo/ftdetect/nfo.vim: ASCII text, with CRLF line terminators
$ file ~/.local/share/nvim/plugged/vim-nfo/ftplugin/nfo.vim 
~/.local/share/nvim/plugged/vim-nfo/ftplugin/nfo.vim: ASCII text, with CRLF line terminators
```

If I checkout the repository directly ie `git clone`, download it as a zip file etc the files only have LFs in there.

**Comment by ghost** [comment]
From  also setting `git config --global core.autocrlf false` was no help.

https://git-scm.com/book/it/v2/Customizing-Git-Git-Configuration

> `core.autocrlf`

> If you’re programming on Windows and working with people who are not (or vice-versa), you’ll probably run into line-ending issues at some point. This is because Windows uses both a carriage-return character and a linefeed character for newlines in its files, whereas Mac and Linux systems use only the linefeed character. This is a subtle but incredibly annoying fact of cross-platform work; many editors on Windows silently replace existing LF-style line endings with CRLF, or insert both line-ending characters when the user hits the enter key.

> Git can handle this by auto-converting CRLF line endings into LF when you add a file to the index, and vice versa when it checks out code onto your filesystem. You can turn on this functionality with the `core.autocrlf` setting. If you’re on a Windows machine, set it to true – this converts LF endings into CRLF when you check out code:

> `$ git config --global core.autocrlf true`

> If you’re on a Linux or Mac system that uses LF line endings, then you don’t want Git to automatically convert them when you check out files; however, if a file with CRLF endings accidentally gets introduced, then you may want Git to fix it. You can tell Git to convert CRLF to LF on commit but not the other way around by setting `core.autocrlf` to input:

> `$ git config --global core.autocrlf input`

> This setup should leave you with CRLF endings in Windows checkouts, but LF endings on Mac and Linux systems and in the repository.

> If you’re a Windows programmer doing a Windows-only project, then you can turn off this functionality, recording the carriage returns in the repository by setting the config value to false:

> `$ git config --global core.autocrlf false`

**Comment by ghost** [comment]
Okay this is super weird. Looking at the VimPlug source https://github.com/junegunn/vim-plug/blob/master/plug.vim#L1019 it looks like it converts all checkouts to be LF.

```vim
 let s:clone_opt .= ' -c core.eol=lf -c core.autocrlf=input'
```

Yet that's precisely not what is happening.

I even tried: 
```
git clone -c core.eol=crlf -c core.autocrlf=false git@github.com:summivox/vim-nfo.git
```
and still got line feeds. I might ask them why this is happening.

**Comment by ghost** [comment]
I figured it out and I am so retarded. 🙃 So I was checking out from https://github.com/vim-scripts/vim-nfo/ it turns out they have introduced the CR+LFs. I had accidentally forgotten I was using that repo in my vimrc. I shall change it over to this one immediately.

**Comment by summivox** [comment]
Lol nice investigation! I didn't even know there's a mirror somewhere out there 🤔

**Comment by ghost** [comment]
Looks like an old one at that based on https://github.com/summivox/vim-nfo/commit/0a09b638b3f60f18d29cf75ec84261a63edab8a7
